services:
  next-app:
    image: gallery--next-app
    build: ./next

    environment:
      POSTGRES_URL: postgres
      EMBEDAPIURL: embedapi
      QDRANTDB: qdrantdb
      APP_DATA: /data

    ports:
      - 3000:3000

    volumes:
      - ./data:/data

    restart: always

  # worker:
  #   image: gallery--worker
  #   build: ./Worker

  #   environment:
  #     - RABBITMQ_HOST=messagequeue
  #   volumes:
  #     - ./data:/data


  messagequeue:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI

  # embedapi:
  #   image: gallery--embed-api
  #   build: ./EmbedAPI

  qdrantdb:
    image: qdrant/qdrant

  postgres:
    image: postgres:alpine

    environment:
      POSTGRES_USER: gallery
      POSTGRES_PASSWORD: gallery
      POSTGRES_DB: gallerydb

    ports:
      - 5432:5432

    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
    driver: local
  qdrant_storage:
    driver: local