services:
  next-app:
    image: gallery--next-app
    build: ./next

    environment:
      EMBEDAPIURL: embedapi
      RABBITMQ_HOST: messagequeue
      QDRANTDB: qdrantdb
      APP_DATA: /data
      PGHOST: postgres
      PGUSER: gallery
      PGPASSWORD: gallery
      PGDATABASE: gallerydb

    ports:
      - 3000:3000

    volumes:
      - ./data:/data

    restart: always

    depends_on:
      messagequeue:
        condition: service_healthy
      

  python-worker:
    image: gallery--python-worker
    
    build: ./Worker

    environment:
      RABBITMQ_HOST: messagequeue
      POSTGRES_HOST: postgres
      APP_DATA: data
      POSTGRES_USER: gallery
      POSTGRES_PASSWORD: gallery
      POSTGRES_DB: gallerydb
      QDRANTHOST: qdrantdb
      QDRANTPORT: 6333
      QDRANTCOLLECTION: media
      AMD_VISIBLE_DEVICES: all

    volumes:
      - ./data:/app/data

    ports:
      - 8001:8001

    depends_on:
      messagequeue:
        condition: service_healthy
      postgres:
        condition: service_healthy
      qdrantdb:
        condition: service_started

  messagequeue:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  # embedapi:
  #   image: gallery--embed-api
  #   build: ./EmbedAPI

  qdrantdb:
    image: qdrant/qdrant

    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API

    volumes:
      - qdrant_storage:/qdrant/storage
      - ./data/qdrant/snapshots:/qdrant/snapshots

    environment:
      QDRANT__LOG_LEVEL: INFO
      QDRANT__STORAGE__ON_DISK_PAYLOAD: "true"

    restart: always


  postgres:
    image: postgres:alpine

    environment:
      POSTGRES_USER: gallery
      POSTGRES_PASSWORD: gallery
      POSTGRES_DB: gallerydb

    ports:
      - 5432:5432

    volumes:
      - pgdata:/var/lib/postgresql/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  nginx:
    image: nginx-alpine
    build: ./nginx
    ports:
      - 8000:8000
    volumes:
      - ./nginx/conf/nginx.config:/etc/nginx/nginx.conf:ro
      - ./data:/data
    depends_on:
      mediaserver:
        condition: service_started
      next-app:
        condition: service_started
    restart: on-failure

  mediaserver:
    image: media-server
    build: ./MediaServer
    
    environment:
      JWT_SECRET_KEY: CHANGE_ME_TO_A_STRONG_SECRET_KEY
      EMBEDAPIURL: embedapi
      RABBITMQ_HOST: messagequeue
      QDRANTHOST: qdrantdb
      QDRANTPORT: 6334
      QDRANTCOLLECTION: media
      APP_DATA: data
      PGHOST: postgres
      PGUSER: gallery
      PGPASSWORD: gallery
      PGDATABASE: gallerydb
      RABBITUSER: guest
      RABBITPASSWORD: guest
      RABBITHOST: messagequeue
      RABBITPORT: 5672
      PRODUCTION: "false"

      
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
    depends_on:
      messagequeue:
        condition: service_healthy
      postgres:
        condition: service_healthy
      qdrantdb:
        condition: service_started
    restart: on-failure
    
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}


volumes:
  pgdata:
    driver: local
  qdrant_storage:
    driver: local
  # data:
  #   driver: local