// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/me": {
            "get": {
                "description": "Returns the authenticated user's UUID, username, and account creation timestamp. Requires a valid auth_token cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current user info",
                "responses": {
                    "200": {
                        "description": "uuid, username, created_at",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/collection": {
            "post": {
                "description": "Creates a new collection owned by the authenticated user. Returns 201 with the new collection UUID as plain text.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Creation"
                ],
                "summary": "Create a new collection",
                "parameters": [
                    {
                        "description": "Collection name, description, and optional thumbnail UUID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/collection.NewCollection"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/collection/{collection_id}": {
            "get": {
                "description": "Returns full metadata for a single collection the user has access to. Returns 403 if the user lacks permission (requires at least basicviewerpermlevel).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Get collection info by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of the collection",
                        "name": "collection_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Array of collection row maps",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Adds one or more images (by UUID) to an existing collection. The caller must own the images and have content-editor permission on the collection. Returns 201 on success.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Creation"
                ],
                "summary": "Insert images into a collection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of the collection",
                        "name": "collection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Array of image UUIDs to insert",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/collection.CollectionUpsertDelFormat"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Permanently deletes a collection owned by the authenticated user. Requires owner-level permission. Returns 204 on success.",
                "tags": [
                    "Deletion"
                ],
                "summary": "Delete a collection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of the collection",
                        "name": "collection_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/collection/{collection_id}/contents": {
            "get": {
                "description": "Returns a paginated list of images belonging to the specified collection, ordered by date added. Supports ` + "`" + `want` + "`" + `, ` + "`" + `offset` + "`" + `, and ` + "`" + `limit` + "`" + ` query parameters. The ` + "`" + `want` + "`" + ` parameter is a dash-separated list of fields (e.g. ` + "`" + `uuid-original_url-thumbnail_url-preview_url-created_at` + "`" + `). Requires content-viewer permission on the collection.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Get collection image contents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of the collection",
                        "name": "collection_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Dash-separated list of fields to return (e.g. uuid-original_url-thumbnail_url)",
                        "name": "want",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of entries to skip",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of entries to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated content array with optional next URL",
                        "schema": {
                            "$ref": "#/definitions/serverutils.PaginatedResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/gms/collection": {
            "get": {
                "description": "Returns a paginated list of all collections the authenticated user has any level of access to, ordered by creation date descending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "List available collections",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of entries to skip",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of entries to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "content array of { uuid, created_at, name, description, thumbnail_url }",
                        "schema": {
                            "$ref": "#/definitions/serverutils.PaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/gms/media": {
            "get": {
                "description": "Query for media available to a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Query for media test for changs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset from the first of an ordered list",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of entries returned",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Which order is it in",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Which attribute are the entries ordered by",
                        "name": "by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Which attributes are wanted in the response",
                        "name": "want",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "Upload images via form data in the field \"files\"",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Creation"
                ],
                "summary": "Upload images",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/gms/media/query": {
            "post": {
                "description": "Query for by word or filter",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Query media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Text to search for",
                        "name": "text_query",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/gms/media/suggestions": {
            "get": {
                "description": "Query for media similar to a specified uuid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Get media suggestions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "uuid of the root media",
                        "name": "uuid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/gms/media/{type}/{id}": {
            "get": {
                "description": "Retrieve a media file by its UUID and type. Returns the file via X-Accel-Redirect (served by nginx). Returns 403 if the authenticated user does not own the media.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Get media file by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Media type (e.g. thumbnail, original)",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "UUID of the media item",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticate with username and password. Sets an HttpOnly cookie named auth_token (JWT, 7-day expiry) on success and returns the user UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Log in",
                "parameters": [
                    {
                        "description": "Username and password",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AuthHandler.UserCredential"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "userid field contains the user UUID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/media/delete": {
            "post": {
                "description": "Delete one or more images owned by the authenticated user. Only images whose owner_uuid matches the caller are deleted. Returns 204 on success.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Deletion"
                ],
                "summary": "Delete media by ID",
                "parameters": [
                    {
                        "description": "List of image UUIDs to delete",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mediahandler.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/signup": {
            "post": {
                "description": "Create a new user account with a username and password. Also creates a default collection for the user. Returns 201 on success.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Username and password",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AuthHandler.UserCredential"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "AuthHandler.UserCredential": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "collection.CollectionUpsertDelFormat": {
            "type": "object",
            "properties": {
                "image_uuids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "collection.NewCollection": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "thumbnail_uuid": {
                    "type": "string"
                }
            }
        },
        "mediahandler.DeleteRequest": {
            "type": "object",
            "properties": {
                "delete_id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "serverutils.PaginatedResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {}
                    }
                },
                "next": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Media Server API",
	Description:      "API for interacting with the media server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
