// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/gms/collection": {
            "get": {
                "description": "Query for all available collections to a specific user by the parameter specified",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Query for available collections",
                "parameters": [
                    {
                        "type": "string",
                        "description": "What attributes are wanted in the response",
                        "name": "want",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offsets from the first response table order",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "How many entries is wanted in the response",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "Create a new collection entry with a specified name and description",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Creation"
                ],
                "summary": "Create a new collection",
                "parameters": [
                    {
                        "description": "The collection data to create",
                        "name": "collection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/collection.NewCollection"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/collection.NewCollection"
                        }
                    }
                }
            }
        },
        "/gms/media": {
            "get": {
                "description": "Query for media available to a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Query for media test for changs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset from the first of an ordered list",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of entries returned",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Which order is it in",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Which attribute are the entries ordered by",
                        "name": "by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Which attributes are wanted in the response",
                        "name": "want",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "Upload images via form data in the field \"files\"",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Creation"
                ],
                "summary": "Upload images",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/gms/media/query": {
            "get": {
                "description": "Query for by word or filter",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Query media",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Text to search for",
                        "name": "text_query",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/gms/media/suggestions": {
            "get": {
                "description": "Query for media similar to a specified uuid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Query"
                ],
                "summary": "Get media suggestions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "uuid of the root media",
                        "name": "uuid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "collection.NewCollection": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Media Server API",
	Description:      "API for interacting with the media server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
