FROM python:3.13-slim AS builder

# Install build dependencies
WORKDIR /app

RUN pip install --upgrade pip setuptools wheel

COPY deps.txt .
RUN pip install -r deps.txt

FROM python:3.13-slim AS runner

WORKDIR /app
COPY --from=builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY . .

CMD ["python", "main.py"]